version: "2"

linters:
  disable:
    - goconst
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: views/.*\.go
        text: "ST1001: should not use dot imports"
  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.Tx).Rollback
        - (*github.com/starfederation/datastar-go/datastar.ServerSentEventGenerator).Redirect
        - (net/http.ResponseWriter).Write
