// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createCPUSampleQuery = `-- name: CreateCPUSampleQuery :exec
INSERT INTO cpu_samples (
    observed_at,
    used_percent,
    cores_logical,
    cores_physical,
    per_core_percent,
    load_1m,
    load_5m,
    load_15m
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type CreateCPUSampleQueryParams struct {
	ObservedAt     string  `db:"observed_at"`
	UsedPercent    float64 `db:"used_percent"`
	CoresLogical   int64   `db:"cores_logical"`
	CoresPhysical  int64   `db:"cores_physical"`
	PerCorePercent string  `db:"per_core_percent"`
	Load1m         float64 `db:"load_1m"`
	Load5m         float64 `db:"load_5m"`
	Load15m        float64 `db:"load_15m"`
}

func (q *Queries) CreateCPUSampleQuery(ctx context.Context, arg CreateCPUSampleQueryParams) error {
	_, err := q.db.ExecContext(ctx, createCPUSampleQuery,
		arg.ObservedAt,
		arg.UsedPercent,
		arg.CoresLogical,
		arg.CoresPhysical,
		arg.PerCorePercent,
		arg.Load1m,
		arg.Load5m,
		arg.Load15m,
	)
	return err
}

const createDiskSampleQuery = `-- name: CreateDiskSampleQuery :exec
INSERT INTO disk_samples (
    observed_at,
    is_total,
    device,
    mount,
    filesystem,
    used_percent,
    used_bytes,
    free_bytes,
    total_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type CreateDiskSampleQueryParams struct {
	ObservedAt  string  `db:"observed_at"`
	IsTotal     int64   `db:"is_total"`
	Device      string  `db:"device"`
	Mount       string  `db:"mount"`
	Filesystem  string  `db:"filesystem"`
	UsedPercent float64 `db:"used_percent"`
	UsedBytes   int64   `db:"used_bytes"`
	FreeBytes   int64   `db:"free_bytes"`
	TotalBytes  int64   `db:"total_bytes"`
}

func (q *Queries) CreateDiskSampleQuery(ctx context.Context, arg CreateDiskSampleQueryParams) error {
	_, err := q.db.ExecContext(ctx, createDiskSampleQuery,
		arg.ObservedAt,
		arg.IsTotal,
		arg.Device,
		arg.Mount,
		arg.Filesystem,
		arg.UsedPercent,
		arg.UsedBytes,
		arg.FreeBytes,
		arg.TotalBytes,
	)
	return err
}

const createMemorySampleQuery = `-- name: CreateMemorySampleQuery :exec
INSERT INTO memory_samples (
    observed_at,
    virtual_used_percent,
    virtual_used_bytes,
    virtual_available_bytes,
    virtual_total_bytes,
    swap_used_percent,
    swap_used_bytes,
    swap_available_bytes,
    swap_total_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type CreateMemorySampleQueryParams struct {
	ObservedAt            string  `db:"observed_at"`
	VirtualUsedPercent    float64 `db:"virtual_used_percent"`
	VirtualUsedBytes      int64   `db:"virtual_used_bytes"`
	VirtualAvailableBytes int64   `db:"virtual_available_bytes"`
	VirtualTotalBytes     int64   `db:"virtual_total_bytes"`
	SwapUsedPercent       float64 `db:"swap_used_percent"`
	SwapUsedBytes         int64   `db:"swap_used_bytes"`
	SwapAvailableBytes    int64   `db:"swap_available_bytes"`
	SwapTotalBytes        int64   `db:"swap_total_bytes"`
}

func (q *Queries) CreateMemorySampleQuery(ctx context.Context, arg CreateMemorySampleQueryParams) error {
	_, err := q.db.ExecContext(ctx, createMemorySampleQuery,
		arg.ObservedAt,
		arg.VirtualUsedPercent,
		arg.VirtualUsedBytes,
		arg.VirtualAvailableBytes,
		arg.VirtualTotalBytes,
		arg.SwapUsedPercent,
		arg.SwapUsedBytes,
		arg.SwapAvailableBytes,
		arg.SwapTotalBytes,
	)
	return err
}

const deleteOldCPUSamplesQuery = `-- name: DeleteOldCPUSamplesQuery :exec
DELETE FROM cpu_samples
WHERE observed_at < ?1
`

func (q *Queries) DeleteOldCPUSamplesQuery(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, deleteOldCPUSamplesQuery, cutoff)
	return err
}

const deleteOldDiskSamplesQuery = `-- name: DeleteOldDiskSamplesQuery :exec
DELETE FROM disk_samples
WHERE observed_at < ?1
`

func (q *Queries) DeleteOldDiskSamplesQuery(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, deleteOldDiskSamplesQuery, cutoff)
	return err
}

const deleteOldMemorySamplesQuery = `-- name: DeleteOldMemorySamplesQuery :exec
DELETE FROM memory_samples
WHERE observed_at < ?1
`

func (q *Queries) DeleteOldMemorySamplesQuery(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, deleteOldMemorySamplesQuery, cutoff)
	return err
}
