// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_memory_samples.sql

package db

import (
	"context"
)

const getLatestMemorySample = `-- name: GetLatestMemorySample :one
SELECT memory_samples.id, memory_samples.observed_at, memory_samples.virtual_used_percent, memory_samples.virtual_used_bytes, memory_samples.virtual_available_bytes, memory_samples.virtual_total_bytes, memory_samples.swap_used_percent, memory_samples.swap_used_bytes, memory_samples.swap_available_bytes, memory_samples.swap_total_bytes
FROM memory_samples
ORDER BY observed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMemorySample(ctx context.Context) (MemorySample, error) {
	row := q.queryRow(ctx, q.getLatestMemorySampleStmt, getLatestMemorySample)
	var i MemorySample
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.VirtualUsedPercent,
		&i.VirtualUsedBytes,
		&i.VirtualAvailableBytes,
		&i.VirtualTotalBytes,
		&i.SwapUsedPercent,
		&i.SwapUsedBytes,
		&i.SwapAvailableBytes,
		&i.SwapTotalBytes,
	)
	return i, err
}

const listMemorySamplesSince = `-- name: ListMemorySamplesSince :many
SELECT memory_samples.id, memory_samples.observed_at, memory_samples.virtual_used_percent, memory_samples.virtual_used_bytes, memory_samples.virtual_available_bytes, memory_samples.virtual_total_bytes, memory_samples.swap_used_percent, memory_samples.swap_used_bytes, memory_samples.swap_available_bytes, memory_samples.swap_total_bytes
FROM memory_samples
WHERE observed_at >= ?1
ORDER BY observed_at
`

func (q *Queries) ListMemorySamplesSince(ctx context.Context, since string) ([]MemorySample, error) {
	rows, err := q.query(ctx, q.listMemorySamplesSinceStmt, listMemorySamplesSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemorySample
	for rows.Next() {
		var i MemorySample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.VirtualUsedPercent,
			&i.VirtualUsedBytes,
			&i.VirtualAvailableBytes,
			&i.VirtualTotalBytes,
			&i.SwapUsedPercent,
			&i.SwapUsedBytes,
			&i.SwapAvailableBytes,
			&i.SwapTotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMemorySample = `-- name: createMemorySample :exec
INSERT INTO memory_samples (
    observed_at,
    virtual_used_percent,
    virtual_used_bytes,
    virtual_available_bytes,
    virtual_total_bytes,
    swap_used_percent,
    swap_used_bytes,
    swap_available_bytes,
    swap_total_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type createMemorySampleParams struct {
	ObservedAt            string  `db:"observed_at"`
	VirtualUsedPercent    float64 `db:"virtual_used_percent"`
	VirtualUsedBytes      int64   `db:"virtual_used_bytes"`
	VirtualAvailableBytes int64   `db:"virtual_available_bytes"`
	VirtualTotalBytes     int64   `db:"virtual_total_bytes"`
	SwapUsedPercent       float64 `db:"swap_used_percent"`
	SwapUsedBytes         int64   `db:"swap_used_bytes"`
	SwapAvailableBytes    int64   `db:"swap_available_bytes"`
	SwapTotalBytes        int64   `db:"swap_total_bytes"`
}

func (q *Queries) createMemorySample(ctx context.Context, arg createMemorySampleParams) error {
	_, err := q.exec(ctx, q.createMemorySampleStmt, createMemorySample,
		arg.ObservedAt,
		arg.VirtualUsedPercent,
		arg.VirtualUsedBytes,
		arg.VirtualAvailableBytes,
		arg.VirtualTotalBytes,
		arg.SwapUsedPercent,
		arg.SwapUsedBytes,
		arg.SwapAvailableBytes,
		arg.SwapTotalBytes,
	)
	return err
}

const deleteOldMemorySamples = `-- name: deleteOldMemorySamples :exec
DELETE FROM memory_samples
WHERE observed_at < ?1
`

func (q *Queries) deleteOldMemorySamples(ctx context.Context, cutoff string) error {
	_, err := q.exec(ctx, q.deleteOldMemorySamplesStmt, deleteOldMemorySamples, cutoff)
	return err
}
