// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_users.sql

package db

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT users.id, users.team_id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT users.id, users.team_id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: createUser :one
INSERT INTO users (team_id, email, password_hash)
VALUES (?1, ?2, ?3)
RETURNING id, team_id, email, password_hash, created_at, updated_at
`

type createUserParams struct {
	TeamID       int64  `db:"team_id"`
	Email        string `db:"email"`
	PasswordHash string `db:"password_hash"`
}

func (q *Queries) createUser(ctx context.Context, arg createUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.TeamID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
