// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_sessions.sql

package db

import (
	"context"
	"time"
)

const commitSession = `-- name: commitSession :exec
INSERT INTO sessions (token, data, expiry)
VALUES (?1, ?2, ?3)
ON CONFLICT(token) DO UPDATE SET data = excluded.data, expiry = excluded.expiry
`

type commitSessionParams struct {
	Token  string    `db:"token"`
	Data   []byte    `db:"data"`
	Expiry time.Time `db:"expiry"`
}

func (q *Queries) commitSession(ctx context.Context, arg commitSessionParams) error {
	_, err := q.exec(ctx, q.commitSessionStmt, commitSession, arg.Token, arg.Data, arg.Expiry)
	return err
}

const deleteSession = `-- name: deleteSession :exec
DELETE FROM sessions
WHERE token = ?1
`

func (q *Queries) deleteSession(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, token)
	return err
}

const findSession = `-- name: findSession :one
SELECT data
FROM sessions
WHERE token = ?1
AND expiry > ?2
`

type findSessionParams struct {
	Token string    `db:"token"`
	Now   time.Time `db:"now"`
}

func (q *Queries) findSession(ctx context.Context, arg findSessionParams) ([]byte, error) {
	row := q.queryRow(ctx, q.findSessionStmt, findSession, arg.Token, arg.Now)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
