// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const addWorkspaceMemberQuery = `-- name: AddWorkspaceMemberQuery :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES (?1, ?2, ?3)
`

type AddWorkspaceMemberQueryParams struct {
	WorkspaceID int64  `db:"workspace_id"`
	UserID      int64  `db:"user_id"`
	Role        string `db:"role"`
}

func (q *Queries) AddWorkspaceMemberQuery(ctx context.Context, arg AddWorkspaceMemberQueryParams) error {
	_, err := q.db.ExecContext(ctx, addWorkspaceMemberQuery, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const commitSessionQuery = `-- name: CommitSessionQuery :exec
INSERT INTO sessions (token, data, expiry)
VALUES (?1, ?2, ?3)
ON CONFLICT(token) DO UPDATE SET data = excluded.data, expiry = excluded.expiry
`

type CommitSessionQueryParams struct {
	Token  string    `db:"token"`
	Data   []byte    `db:"data"`
	Expiry time.Time `db:"expiry"`
}

func (q *Queries) CommitSessionQuery(ctx context.Context, arg CommitSessionQueryParams) error {
	_, err := q.db.ExecContext(ctx, commitSessionQuery, arg.Token, arg.Data, arg.Expiry)
	return err
}

const createAgentQuery = `-- name: CreateAgentQuery :one
INSERT INTO agents (workspace_id, widget_id, name)
VALUES (?1, ?2, ?3)
RETURNING id, workspace_id, widget_id, name, created_at, updated_at
`

type CreateAgentQueryParams struct {
	WorkspaceID int64  `db:"workspace_id"`
	WidgetID    string `db:"widget_id"`
	Name        string `db:"name"`
}

func (q *Queries) CreateAgentQuery(ctx context.Context, arg CreateAgentQueryParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgentQuery, arg.WorkspaceID, arg.WidgetID, arg.Name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WidgetID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessageQuery = `-- name: CreateMessageQuery :exec
INSERT INTO messages (conversation_id, role, text)
VALUES (?1, ?2, ?3)
`

type CreateMessageQueryParams struct {
	ConversationID int64  `db:"conversation_id"`
	Role           string `db:"role"`
	Text           string `db:"text"`
}

func (q *Queries) CreateMessageQuery(ctx context.Context, arg CreateMessageQueryParams) error {
	_, err := q.db.ExecContext(ctx, createMessageQuery, arg.ConversationID, arg.Role, arg.Text)
	return err
}

const createSourceWebsiteQuery = `-- name: CreateSourceWebsiteQuery :one
INSERT INTO source_websites (workspace_id, root_url)
VALUES (?1, ?2)
RETURNING source_id, workspace_id, root_url, name, favicon_url, theme_color, created_at, updated_at
`

type CreateSourceWebsiteQueryParams struct {
	WorkspaceID int64  `db:"workspace_id"`
	RootURL     string `db:"root_url"`
}

func (q *Queries) CreateSourceWebsiteQuery(ctx context.Context, arg CreateSourceWebsiteQueryParams) (SourceWebsite, error) {
	row := q.db.QueryRowContext(ctx, createSourceWebsiteQuery, arg.WorkspaceID, arg.RootURL)
	var i SourceWebsite
	err := row.Scan(
		&i.SourceID,
		&i.WorkspaceID,
		&i.RootURL,
		&i.Name,
		&i.FaviconURL,
		&i.ThemeColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserQuery = `-- name: CreateUserQuery :one
INSERT INTO users (email, password_hash)
VALUES (?1, ?2)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateUserQueryParams struct {
	Email        string `db:"email"`
	PasswordHash string `db:"password_hash"`
}

func (q *Queries) CreateUserQuery(ctx context.Context, arg CreateUserQueryParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserQuery, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceQuery = `-- name: CreateWorkspaceQuery :one
INSERT INTO workspaces (name)
VALUES (?1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWorkspaceQuery(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaceQuery, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionQuery = `-- name: DeleteSessionQuery :exec
DELETE FROM sessions
WHERE token = ?1
`

func (q *Queries) DeleteSessionQuery(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionQuery, token)
	return err
}

const findSessionQuery = `-- name: FindSessionQuery :one
SELECT data
FROM sessions
WHERE token = ?1
AND expiry > ?2
`

type FindSessionQueryParams struct {
	Token string    `db:"token"`
	Now   time.Time `db:"now"`
}

func (q *Queries) FindSessionQuery(ctx context.Context, arg FindSessionQueryParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, findSessionQuery, arg.Token, arg.Now)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getAgentQuery = `-- name: GetAgentQuery :one
SELECT agents.id, agents.workspace_id, agents.widget_id, agents.name, agents.created_at, agents.updated_at
FROM agents
WHERE workspace_id = ?1 AND id = ?2
`

type GetAgentQueryParams struct {
	WorkspaceID int64 `db:"workspace_id"`
	AgentID     int64 `db:"agent_id"`
}

type GetAgentQueryRow struct {
	Agent Agent `db:"agent"`
}

func (q *Queries) GetAgentQuery(ctx context.Context, arg GetAgentQueryParams) (GetAgentQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentQuery, arg.WorkspaceID, arg.AgentID)
	var i GetAgentQueryRow
	err := row.Scan(
		&i.Agent.ID,
		&i.Agent.WorkspaceID,
		&i.Agent.WidgetID,
		&i.Agent.Name,
		&i.Agent.CreatedAt,
		&i.Agent.UpdatedAt,
	)
	return i, err
}

const getSourceWebsiteQuery = `-- name: GetSourceWebsiteQuery :one
SELECT source_websites.source_id, source_websites.workspace_id, source_websites.root_url, source_websites.name, source_websites.favicon_url, source_websites.theme_color, source_websites.created_at, source_websites.updated_at
FROM source_websites
WHERE workspace_id = ?1 AND root_url = ?2
`

type GetSourceWebsiteQueryParams struct {
	WorkspaceID int64  `db:"workspace_id"`
	RootURL     string `db:"root_url"`
}

type GetSourceWebsiteQueryRow struct {
	SourceWebsite SourceWebsite `db:"source_website"`
}

func (q *Queries) GetSourceWebsiteQuery(ctx context.Context, arg GetSourceWebsiteQueryParams) (GetSourceWebsiteQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getSourceWebsiteQuery, arg.WorkspaceID, arg.RootURL)
	var i GetSourceWebsiteQueryRow
	err := row.Scan(
		&i.SourceWebsite.SourceID,
		&i.SourceWebsite.WorkspaceID,
		&i.SourceWebsite.RootURL,
		&i.SourceWebsite.Name,
		&i.SourceWebsite.FaviconURL,
		&i.SourceWebsite.ThemeColor,
		&i.SourceWebsite.CreatedAt,
		&i.SourceWebsite.UpdatedAt,
	)
	return i, err
}

const getUserByEmailQuery = `-- name: GetUserByEmailQuery :one
SELECT users.id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE email = ?1
`

type GetUserByEmailQueryRow struct {
	User User `db:"user"`
}

func (q *Queries) GetUserByEmailQuery(ctx context.Context, email string) (GetUserByEmailQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailQuery, email)
	var i GetUserByEmailQueryRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getUserByIDQuery = `-- name: GetUserByIDQuery :one
SELECT users.id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE id = ?1
`

type GetUserByIDQueryRow struct {
	User User `db:"user"`
}

func (q *Queries) GetUserByIDQuery(ctx context.Context, id int64) (GetUserByIDQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDQuery, id)
	var i GetUserByIDQueryRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getUserDefaultWorkspaceQuery = `-- name: GetUserDefaultWorkspaceQuery :one
SELECT workspaces.id, workspaces.name, workspaces.created_at, workspaces.updated_at
FROM workspaces
JOIN workspace_members ON workspace_members.workspace_id = workspaces.id
WHERE workspace_members.user_id = ?1
ORDER BY workspace_members.created_at, workspaces.id
LIMIT 1
`

type GetUserDefaultWorkspaceQueryRow struct {
	Workspace Workspace `db:"workspace"`
}

func (q *Queries) GetUserDefaultWorkspaceQuery(ctx context.Context, userID int64) (GetUserDefaultWorkspaceQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getUserDefaultWorkspaceQuery, userID)
	var i GetUserDefaultWorkspaceQueryRow
	err := row.Scan(
		&i.Workspace.ID,
		&i.Workspace.Name,
		&i.Workspace.CreatedAt,
		&i.Workspace.UpdatedAt,
	)
	return i, err
}

const listMessagesQuery = `-- name: ListMessagesQuery :many
SELECT messages.id, messages.conversation_id, messages.role, messages.text, messages.created_at
FROM messages
WHERE conversation_id = ?1
ORDER BY created_at, id
`

type ListMessagesQueryRow struct {
	Message Message `db:"message"`
}

func (q *Queries) ListMessagesQuery(ctx context.Context, conversationID int64) ([]ListMessagesQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesQuery, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesQueryRow
	for rows.Next() {
		var i ListMessagesQueryRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.ConversationID,
			&i.Message.Role,
			&i.Message.Text,
			&i.Message.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversationQuery = `-- name: TouchConversationQuery :exec
UPDATE conversations
SET updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) TouchConversationQuery(ctx context.Context, conversationID int64) error {
	_, err := q.db.ExecContext(ctx, touchConversationQuery, conversationID)
	return err
}

const upsertConversationQuery = `-- name: UpsertConversationQuery :one
INSERT INTO conversations (visitor_id)
VALUES (?1)
ON CONFLICT(visitor_id) DO UPDATE SET updated_at = CURRENT_TIMESTAMP
RETURNING id, visitor_id, created_at, updated_at
`

func (q *Queries) UpsertConversationQuery(ctx context.Context, visitorID string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, upsertConversationQuery, visitorID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.VisitorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSourceWebsitePageQuery = `-- name: UpsertSourceWebsitePageQuery :exec
INSERT INTO source_website_pages (
    source_website_id,
    url,
    title,
    content,
    byte_count
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
ON CONFLICT(source_website_id, url) DO UPDATE SET
    title = excluded.title,
    content = excluded.content,
    byte_count = excluded.byte_count,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSourceWebsitePageQueryParams struct {
	SourceWebsiteID int64  `db:"source_website_id"`
	URL             string `db:"url"`
	Title           string `db:"title"`
	Content         string `db:"content"`
	ByteCount       int64  `db:"byte_count"`
}

func (q *Queries) UpsertSourceWebsitePageQuery(ctx context.Context, arg UpsertSourceWebsitePageQueryParams) error {
	_, err := q.db.ExecContext(ctx, upsertSourceWebsitePageQuery,
		arg.SourceWebsiteID,
		arg.URL,
		arg.Title,
		arg.Content,
		arg.ByteCount,
	)
	return err
}

const upsertVisitorQuery = `-- name: UpsertVisitorQuery :exec
INSERT INTO visitors (id, widget_id)
VALUES (?1, ?2)
ON CONFLICT(id) DO UPDATE SET last_seen_at = CURRENT_TIMESTAMP
`

type UpsertVisitorQueryParams struct {
	VisitorID string `db:"visitor_id"`
	WidgetID  string `db:"widget_id"`
}

func (q *Queries) UpsertVisitorQuery(ctx context.Context, arg UpsertVisitorQueryParams) error {
	_, err := q.db.ExecContext(ctx, upsertVisitorQuery, arg.VisitorID, arg.WidgetID)
	return err
}

const widgetExistsQuery = `-- name: WidgetExistsQuery :one
SELECT 1
FROM agents
WHERE widget_id = ?1
`

func (q *Queries) WidgetExistsQuery(ctx context.Context, widgetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, widgetExistsQuery, widgetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
