// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_disk_samples.sql

package db

import (
	"context"
)

const listDiskSamplesForMountSince = `-- name: ListDiskSamplesForMountSince :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE mount = ?1
  AND observed_at >= ?2
ORDER BY observed_at
`

type ListDiskSamplesForMountSinceParams struct {
	Mount string `db:"mount"`
	Since string `db:"since"`
}

func (q *Queries) ListDiskSamplesForMountSince(ctx context.Context, arg ListDiskSamplesForMountSinceParams) ([]DiskSample, error) {
	rows, err := q.query(ctx, q.listDiskSamplesForMountSinceStmt, listDiskSamplesForMountSince, arg.Mount, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiskSample
	for rows.Next() {
		var i DiskSample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.IsTotal,
			&i.Device,
			&i.Mount,
			&i.Filesystem,
			&i.UsedPercent,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiskSamplesSince = `-- name: ListDiskSamplesSince :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE observed_at >= ?1
ORDER BY observed_at, is_total DESC, mount
`

func (q *Queries) ListDiskSamplesSince(ctx context.Context, since string) ([]DiskSample, error) {
	rows, err := q.query(ctx, q.listDiskSamplesSinceStmt, listDiskSamplesSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiskSample
	for rows.Next() {
		var i DiskSample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.IsTotal,
			&i.Device,
			&i.Mount,
			&i.Filesystem,
			&i.UsedPercent,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDiskSamples = `-- name: ListLatestDiskSamples :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE observed_at = (
    SELECT MAX(observed_at)
    FROM disk_samples
)
ORDER BY is_total DESC, free_bytes, mount
`

func (q *Queries) ListLatestDiskSamples(ctx context.Context) ([]DiskSample, error) {
	rows, err := q.query(ctx, q.listLatestDiskSamplesStmt, listLatestDiskSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiskSample
	for rows.Next() {
		var i DiskSample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.IsTotal,
			&i.Device,
			&i.Mount,
			&i.Filesystem,
			&i.UsedPercent,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDiskSample = `-- name: createDiskSample :exec
INSERT INTO disk_samples (
    observed_at,
    is_total,
    device,
    mount,
    filesystem,
    used_percent,
    used_bytes,
    free_bytes,
    total_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type createDiskSampleParams struct {
	ObservedAt  string  `db:"observed_at"`
	IsTotal     int64   `db:"is_total"`
	Device      string  `db:"device"`
	Mount       string  `db:"mount"`
	Filesystem  string  `db:"filesystem"`
	UsedPercent float64 `db:"used_percent"`
	UsedBytes   int64   `db:"used_bytes"`
	FreeBytes   int64   `db:"free_bytes"`
	TotalBytes  int64   `db:"total_bytes"`
}

func (q *Queries) createDiskSample(ctx context.Context, arg createDiskSampleParams) error {
	_, err := q.exec(ctx, q.createDiskSampleStmt, createDiskSample,
		arg.ObservedAt,
		arg.IsTotal,
		arg.Device,
		arg.Mount,
		arg.Filesystem,
		arg.UsedPercent,
		arg.UsedBytes,
		arg.FreeBytes,
		arg.TotalBytes,
	)
	return err
}

const deleteOldDiskSamples = `-- name: deleteOldDiskSamples :exec
DELETE FROM disk_samples
WHERE observed_at < ?1
`

func (q *Queries) deleteOldDiskSamples(ctx context.Context, cutoff string) error {
	_, err := q.exec(ctx, q.deleteOldDiskSamplesStmt, deleteOldDiskSamples, cutoff)
	return err
}
