// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getAgentByAPIKey = `-- name: GetAgentByAPIKey :one
SELECT agents.id, agents.team_id, agents.name, agents.version, agents.status, agents.host_id, agents.api_key, agents.created_at, agents.updated_at
FROM agents
WHERE api_key = ?1
`

func (q *Queries) GetAgentByAPIKey(ctx context.Context, apiKey AgentAPIKey) (Agent, error) {
	row := q.queryRow(ctx, q.getAgentByAPIKeyStmt, getAgentByAPIKey, apiKey)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.HostID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentForTeam = `-- name: GetAgentForTeam :one
SELECT agents.id, agents.team_id, agents.name, agents.version, agents.status, agents.host_id, agents.api_key, agents.created_at, agents.updated_at
FROM agents
WHERE id = ?1
AND team_id = ?2
`

type GetAgentForTeamParams struct {
	ID     AgentID `db:"id"`
	TeamID TeamID  `db:"team_id"`
}

func (q *Queries) GetAgentForTeam(ctx context.Context, arg GetAgentForTeamParams) (Agent, error) {
	row := q.queryRow(ctx, q.getAgentForTeamStmt, getAgentForTeam, arg.ID, arg.TeamID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.HostID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCPUSample = `-- name: GetLatestCPUSample :one
SELECT cpu_samples.id, cpu_samples.observed_at, cpu_samples.used_percent, cpu_samples.cores_logical, cpu_samples.cores_physical, cpu_samples.per_core_percent, cpu_samples.load_1m, cpu_samples.load_5m, cpu_samples.load_15m
FROM cpu_samples
ORDER BY observed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCPUSample(ctx context.Context) (CpuSample, error) {
	row := q.queryRow(ctx, q.getLatestCPUSampleStmt, getLatestCPUSample)
	var i CpuSample
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.UsedPercent,
		&i.CoresLogical,
		&i.CoresPhysical,
		&i.PerCorePercent,
		&i.Load1m,
		&i.Load5m,
		&i.Load15m,
	)
	return i, err
}

const getLatestMemorySample = `-- name: GetLatestMemorySample :one
SELECT memory_samples.id, memory_samples.observed_at, memory_samples.virtual_used_percent, memory_samples.virtual_used_bytes, memory_samples.virtual_available_bytes, memory_samples.virtual_total_bytes, memory_samples.swap_used_percent, memory_samples.swap_used_bytes, memory_samples.swap_available_bytes, memory_samples.swap_total_bytes
FROM memory_samples
ORDER BY observed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMemorySample(ctx context.Context) (MemorySample, error) {
	row := q.queryRow(ctx, q.getLatestMemorySampleStmt, getLatestMemorySample)
	var i MemorySample
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.VirtualUsedPercent,
		&i.VirtualUsedBytes,
		&i.VirtualAvailableBytes,
		&i.VirtualTotalBytes,
		&i.SwapUsedPercent,
		&i.SwapUsedBytes,
		&i.SwapAvailableBytes,
		&i.SwapTotalBytes,
	)
	return i, err
}

const getTeamByAgentAPIKey = `-- name: GetTeamByAgentAPIKey :one
SELECT teams.id, teams.name, teams.created_at, teams.updated_at 
FROM teams
JOIN agents ON agents.team_id = teams.id
WHERE agents.api_key = ?1
`

func (q *Queries) GetTeamByAgentAPIKey(ctx context.Context, agentApiKey AgentAPIKey) (Team, error) {
	row := q.queryRow(ctx, q.getTeamByAgentAPIKeyStmt, getTeamByAgentAPIKey, agentApiKey)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT teams.id, teams.name, teams.created_at, teams.updated_at  
FROM teams
WHERE id = ?1
`

func (q *Queries) GetTeamByID(ctx context.Context, id TeamID) (Team, error) {
	row := q.queryRow(ctx, q.getTeamByIDStmt, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT users.id, users.team_id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT users.id, users.team_id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, id UserID) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsForTeam = `-- name: ListAgentsForTeam :many
SELECT agents.id, agents.team_id, agents.name, agents.version, agents.status, agents.host_id, agents.api_key, agents.created_at, agents.updated_at
FROM agents
WHERE team_id = ?1
AND STATUS != 'deleted'
ORDER BY updated_at DESC
`

func (q *Queries) ListAgentsForTeam(ctx context.Context, teamID TeamID) ([]Agent, error) {
	rows, err := q.query(ctx, q.listAgentsForTeamStmt, listAgentsForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Version,
			&i.Status,
			&i.HostID,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCPUSamplesSince = `-- name: ListCPUSamplesSince :many
SELECT cpu_samples.id, cpu_samples.observed_at, cpu_samples.used_percent, cpu_samples.cores_logical, cpu_samples.cores_physical, cpu_samples.per_core_percent, cpu_samples.load_1m, cpu_samples.load_5m, cpu_samples.load_15m
FROM cpu_samples
WHERE observed_at >= ?1
ORDER BY observed_at
`

func (q *Queries) ListCPUSamplesSince(ctx context.Context, since string) ([]CpuSample, error) {
	rows, err := q.query(ctx, q.listCPUSamplesSinceStmt, listCPUSamplesSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpuSample
	for rows.Next() {
		var i CpuSample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.UsedPercent,
			&i.CoresLogical,
			&i.CoresPhysical,
			&i.PerCorePercent,
			&i.Load1m,
			&i.Load5m,
			&i.Load15m,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiskSamplesForMountSince = `-- name: ListDiskSamplesForMountSince :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE mount = ?1
  AND observed_at >= ?2
ORDER BY observed_at
`

type ListDiskSamplesForMountSinceParams struct {
	Mount string `db:"mount"`
	Since string `db:"since"`
}

func (q *Queries) ListDiskSamplesForMountSince(ctx context.Context, arg ListDiskSamplesForMountSinceParams) ([]DiskSample, error) {
	rows, err := q.query(ctx, q.listDiskSamplesForMountSinceStmt, listDiskSamplesForMountSince, arg.Mount, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiskSample
	for rows.Next() {
		var i DiskSample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.IsTotal,
			&i.Device,
			&i.Mount,
			&i.Filesystem,
			&i.UsedPercent,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiskSamplesSince = `-- name: ListDiskSamplesSince :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE observed_at >= ?1
ORDER BY observed_at, is_total DESC, mount
`

func (q *Queries) ListDiskSamplesSince(ctx context.Context, since string) ([]DiskSample, error) {
	rows, err := q.query(ctx, q.listDiskSamplesSinceStmt, listDiskSamplesSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiskSample
	for rows.Next() {
		var i DiskSample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.IsTotal,
			&i.Device,
			&i.Mount,
			&i.Filesystem,
			&i.UsedPercent,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDiskSamples = `-- name: ListLatestDiskSamples :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE observed_at = (
    SELECT MAX(observed_at)
    FROM disk_samples
)
ORDER BY is_total DESC, free_bytes, mount
`

func (q *Queries) ListLatestDiskSamples(ctx context.Context) ([]DiskSample, error) {
	rows, err := q.query(ctx, q.listLatestDiskSamplesStmt, listLatestDiskSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiskSample
	for rows.Next() {
		var i DiskSample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.IsTotal,
			&i.Device,
			&i.Mount,
			&i.Filesystem,
			&i.UsedPercent,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemorySamplesSince = `-- name: ListMemorySamplesSince :many
SELECT memory_samples.id, memory_samples.observed_at, memory_samples.virtual_used_percent, memory_samples.virtual_used_bytes, memory_samples.virtual_available_bytes, memory_samples.virtual_total_bytes, memory_samples.swap_used_percent, memory_samples.swap_used_bytes, memory_samples.swap_available_bytes, memory_samples.swap_total_bytes
FROM memory_samples
WHERE observed_at >= ?1
ORDER BY observed_at
`

func (q *Queries) ListMemorySamplesSince(ctx context.Context, since string) ([]MemorySample, error) {
	rows, err := q.query(ctx, q.listMemorySamplesSinceStmt, listMemorySamplesSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemorySample
	for rows.Next() {
		var i MemorySample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.VirtualUsedPercent,
			&i.VirtualUsedBytes,
			&i.VirtualAvailableBytes,
			&i.VirtualTotalBytes,
			&i.SwapUsedPercent,
			&i.SwapUsedBytes,
			&i.SwapAvailableBytes,
			&i.SwapTotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentStatusForTeam = `-- name: SetAgentStatusForTeam :exec
UPDATE agents
SET status = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
AND team_id = ?3
`

type SetAgentStatusForTeamParams struct {
	Status AgentStatus `db:"status"`
	ID     AgentID     `db:"id"`
	TeamID TeamID      `db:"team_id"`
}

func (q *Queries) SetAgentStatusForTeam(ctx context.Context, arg SetAgentStatusForTeamParams) error {
	_, err := q.exec(ctx, q.setAgentStatusForTeamStmt, setAgentStatusForTeam, arg.Status, arg.ID, arg.TeamID)
	return err
}

const commitSession = `-- name: commitSession :exec
INSERT INTO sessions (token, data, expiry)
VALUES (?1, ?2, ?3)
ON CONFLICT(token) DO UPDATE SET data = excluded.data, expiry = excluded.expiry
`

type commitSessionParams struct {
	Token  SessionToken `db:"token"`
	Data   []byte       `db:"data"`
	Expiry time.Time    `db:"expiry"`
}

func (q *Queries) commitSession(ctx context.Context, arg commitSessionParams) error {
	_, err := q.exec(ctx, q.commitSessionStmt, commitSession, arg.Token, arg.Data, arg.Expiry)
	return err
}

const createCPUSample = `-- name: createCPUSample :exec
INSERT INTO cpu_samples (
    observed_at,
    used_percent,
    cores_logical,
    cores_physical,
    per_core_percent,
    load_1m,
    load_5m,
    load_15m
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type createCPUSampleParams struct {
	ObservedAt     string  `db:"observed_at"`
	UsedPercent    float64 `db:"used_percent"`
	CoresLogical   int64   `db:"cores_logical"`
	CoresPhysical  int64   `db:"cores_physical"`
	PerCorePercent string  `db:"per_core_percent"`
	Load1m         float64 `db:"load_1m"`
	Load5m         float64 `db:"load_5m"`
	Load15m        float64 `db:"load_15m"`
}

func (q *Queries) createCPUSample(ctx context.Context, arg createCPUSampleParams) error {
	_, err := q.exec(ctx, q.createCPUSampleStmt, createCPUSample,
		arg.ObservedAt,
		arg.UsedPercent,
		arg.CoresLogical,
		arg.CoresPhysical,
		arg.PerCorePercent,
		arg.Load1m,
		arg.Load5m,
		arg.Load15m,
	)
	return err
}

const createDiskSample = `-- name: createDiskSample :exec
INSERT INTO disk_samples (
    observed_at,
    is_total,
    device,
    mount,
    filesystem,
    used_percent,
    used_bytes,
    free_bytes,
    total_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type createDiskSampleParams struct {
	ObservedAt  string  `db:"observed_at"`
	IsTotal     int64   `db:"is_total"`
	Device      string  `db:"device"`
	Mount       string  `db:"mount"`
	Filesystem  string  `db:"filesystem"`
	UsedPercent float64 `db:"used_percent"`
	UsedBytes   int64   `db:"used_bytes"`
	FreeBytes   int64   `db:"free_bytes"`
	TotalBytes  int64   `db:"total_bytes"`
}

func (q *Queries) createDiskSample(ctx context.Context, arg createDiskSampleParams) error {
	_, err := q.exec(ctx, q.createDiskSampleStmt, createDiskSample,
		arg.ObservedAt,
		arg.IsTotal,
		arg.Device,
		arg.Mount,
		arg.Filesystem,
		arg.UsedPercent,
		arg.UsedBytes,
		arg.FreeBytes,
		arg.TotalBytes,
	)
	return err
}

const createMemorySample = `-- name: createMemorySample :exec
INSERT INTO memory_samples (
    observed_at,
    virtual_used_percent,
    virtual_used_bytes,
    virtual_available_bytes,
    virtual_total_bytes,
    swap_used_percent,
    swap_used_bytes,
    swap_available_bytes,
    swap_total_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type createMemorySampleParams struct {
	ObservedAt            string  `db:"observed_at"`
	VirtualUsedPercent    float64 `db:"virtual_used_percent"`
	VirtualUsedBytes      int64   `db:"virtual_used_bytes"`
	VirtualAvailableBytes int64   `db:"virtual_available_bytes"`
	VirtualTotalBytes     int64   `db:"virtual_total_bytes"`
	SwapUsedPercent       float64 `db:"swap_used_percent"`
	SwapUsedBytes         int64   `db:"swap_used_bytes"`
	SwapAvailableBytes    int64   `db:"swap_available_bytes"`
	SwapTotalBytes        int64   `db:"swap_total_bytes"`
}

func (q *Queries) createMemorySample(ctx context.Context, arg createMemorySampleParams) error {
	_, err := q.exec(ctx, q.createMemorySampleStmt, createMemorySample,
		arg.ObservedAt,
		arg.VirtualUsedPercent,
		arg.VirtualUsedBytes,
		arg.VirtualAvailableBytes,
		arg.VirtualTotalBytes,
		arg.SwapUsedPercent,
		arg.SwapUsedBytes,
		arg.SwapAvailableBytes,
		arg.SwapTotalBytes,
	)
	return err
}

const createTeam = `-- name: createTeam :one
INSERT INTO teams (name)
VALUES (?1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) createTeam(ctx context.Context, name string) (Team, error) {
	row := q.queryRow(ctx, q.createTeamStmt, createTeam, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: createUser :one
INSERT INTO users (team_id, email, password_hash)
VALUES (?1, ?2, ?3)
RETURNING id, team_id, email, password_hash, created_at, updated_at
`

type createUserParams struct {
	TeamID       TeamID `db:"team_id"`
	Email        string `db:"email"`
	PasswordHash string `db:"password_hash"`
}

func (q *Queries) createUser(ctx context.Context, arg createUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.TeamID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldCPUSamples = `-- name: deleteOldCPUSamples :exec
DELETE FROM cpu_samples
WHERE observed_at < ?1
`

func (q *Queries) deleteOldCPUSamples(ctx context.Context, cutoff string) error {
	_, err := q.exec(ctx, q.deleteOldCPUSamplesStmt, deleteOldCPUSamples, cutoff)
	return err
}

const deleteOldDiskSamples = `-- name: deleteOldDiskSamples :exec
DELETE FROM disk_samples
WHERE observed_at < ?1
`

func (q *Queries) deleteOldDiskSamples(ctx context.Context, cutoff string) error {
	_, err := q.exec(ctx, q.deleteOldDiskSamplesStmt, deleteOldDiskSamples, cutoff)
	return err
}

const deleteOldMemorySamples = `-- name: deleteOldMemorySamples :exec
DELETE FROM memory_samples
WHERE observed_at < ?1
`

func (q *Queries) deleteOldMemorySamples(ctx context.Context, cutoff string) error {
	_, err := q.exec(ctx, q.deleteOldMemorySamplesStmt, deleteOldMemorySamples, cutoff)
	return err
}

const deleteSession = `-- name: deleteSession :exec
DELETE FROM sessions
WHERE token = ?1
`

func (q *Queries) deleteSession(ctx context.Context, token SessionToken) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, token)
	return err
}

const findSession = `-- name: findSession :one
SELECT data
FROM sessions
WHERE token = ?1
AND expiry > ?2
`

type findSessionParams struct {
	Token SessionToken `db:"token"`
	Now   time.Time    `db:"now"`
}

func (q *Queries) findSession(ctx context.Context, arg findSessionParams) ([]byte, error) {
	row := q.queryRow(ctx, q.findSessionStmt, findSession, arg.Token, arg.Now)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const touchAgentForTeam = `-- name: touchAgentForTeam :execrows
UPDATE agents
SET version = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
AND team_id = ?3
`

type touchAgentForTeamParams struct {
	Version string  `db:"version"`
	ID      AgentID `db:"id"`
	TeamID  TeamID  `db:"team_id"`
}

func (q *Queries) touchAgentForTeam(ctx context.Context, arg touchAgentForTeamParams) (int64, error) {
	result, err := q.exec(ctx, q.touchAgentForTeamStmt, touchAgentForTeam, arg.Version, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAgentHostID = `-- name: updateAgentHostID :exec
UPDATE agents
SET host_id = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type updateAgentHostIDParams struct {
	HostID sql.NullString `db:"host_id"`
	ID     AgentID        `db:"id"`
}

func (q *Queries) updateAgentHostID(ctx context.Context, arg updateAgentHostIDParams) error {
	_, err := q.exec(ctx, q.updateAgentHostIDStmt, updateAgentHostID, arg.HostID, arg.ID)
	return err
}

const upsertAgentForTeam = `-- name: upsertAgentForTeam :one
INSERT INTO agents (id, team_id, name, version, status, api_key)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    version = excluded.version,
    status = excluded.status,
    updated_at = CURRENT_TIMESTAMP
WHERE agents.team_id = excluded.team_id
RETURNING id, team_id, name, version, status, host_id, api_key, created_at, updated_at
`

type upsertAgentForTeamParams struct {
	ID      AgentID     `db:"id"`
	TeamID  TeamID      `db:"team_id"`
	Name    string      `db:"name"`
	Version string      `db:"version"`
	Status  AgentStatus `db:"status"`
	ApiKey  AgentAPIKey `db:"api_key"`
}

func (q *Queries) upsertAgentForTeam(ctx context.Context, arg upsertAgentForTeamParams) (Agent, error) {
	row := q.queryRow(ctx, q.upsertAgentForTeamStmt, upsertAgentForTeam,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Version,
		arg.Status,
		arg.ApiKey,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.HostID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
