// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_agents.sql

package db

import (
	"context"
	"database/sql"
)

const getAgentByAPIKey = `-- name: GetAgentByAPIKey :one
SELECT agents.id, agents.team_id, agents.name, agents.version, agents.status, agents.host_id, agents.api_key, agents.created_at, agents.updated_at
FROM agents
WHERE api_key = ?1
`

func (q *Queries) GetAgentByAPIKey(ctx context.Context, apiKey string) (Agent, error) {
	row := q.queryRow(ctx, q.getAgentByAPIKeyStmt, getAgentByAPIKey, apiKey)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.HostID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentForTeam = `-- name: GetAgentForTeam :one
SELECT agents.id, agents.team_id, agents.name, agents.version, agents.status, agents.host_id, agents.api_key, agents.created_at, agents.updated_at
FROM agents
WHERE id = ?1
AND team_id = ?2
`

type GetAgentForTeamParams struct {
	ID     string `db:"id"`
	TeamID int64  `db:"team_id"`
}

func (q *Queries) GetAgentForTeam(ctx context.Context, arg GetAgentForTeamParams) (Agent, error) {
	row := q.queryRow(ctx, q.getAgentForTeamStmt, getAgentForTeam, arg.ID, arg.TeamID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.HostID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsForTeam = `-- name: ListAgentsForTeam :many
SELECT agents.id, agents.team_id, agents.name, agents.version, agents.status, agents.host_id, agents.api_key, agents.created_at, agents.updated_at
FROM agents
WHERE team_id = ?1
AND STATUS != 'deleted'
ORDER BY updated_at DESC
`

func (q *Queries) ListAgentsForTeam(ctx context.Context, teamID int64) ([]Agent, error) {
	rows, err := q.query(ctx, q.listAgentsForTeamStmt, listAgentsForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Version,
			&i.Status,
			&i.HostID,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentStatusForTeam = `-- name: setAgentStatusForTeam :exec
UPDATE agents
SET status = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
AND team_id = ?3
`

type setAgentStatusForTeamParams struct {
	Status string `db:"status"`
	ID     string `db:"id"`
	TeamID int64  `db:"team_id"`
}

func (q *Queries) setAgentStatusForTeam(ctx context.Context, arg setAgentStatusForTeamParams) error {
	_, err := q.exec(ctx, q.setAgentStatusForTeamStmt, setAgentStatusForTeam, arg.Status, arg.ID, arg.TeamID)
	return err
}

const touchAgentForTeam = `-- name: touchAgentForTeam :execrows
UPDATE agents
SET version = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
AND team_id = ?3
`

type touchAgentForTeamParams struct {
	Version string `db:"version"`
	ID      string `db:"id"`
	TeamID  int64  `db:"team_id"`
}

func (q *Queries) touchAgentForTeam(ctx context.Context, arg touchAgentForTeamParams) (int64, error) {
	result, err := q.exec(ctx, q.touchAgentForTeamStmt, touchAgentForTeam, arg.Version, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAgentHostID = `-- name: updateAgentHostID :exec
UPDATE agents
SET host_id = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type updateAgentHostIDParams struct {
	HostID sql.NullString `db:"host_id"`
	ID     string         `db:"id"`
}

func (q *Queries) updateAgentHostID(ctx context.Context, arg updateAgentHostIDParams) error {
	_, err := q.exec(ctx, q.updateAgentHostIDStmt, updateAgentHostID, arg.HostID, arg.ID)
	return err
}

const upsertAgentForTeam = `-- name: upsertAgentForTeam :one
INSERT INTO agents (id, team_id, name, version, status, api_key)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    version = excluded.version,
    status = excluded.status,
    updated_at = CURRENT_TIMESTAMP
WHERE agents.team_id = excluded.team_id
RETURNING id, team_id, name, version, status, host_id, api_key, created_at, updated_at
`

type upsertAgentForTeamParams struct {
	ID      string `db:"id"`
	TeamID  int64  `db:"team_id"`
	Name    string `db:"name"`
	Version string `db:"version"`
	Status  string `db:"status"`
	ApiKey  string `db:"api_key"`
}

func (q *Queries) upsertAgentForTeam(ctx context.Context, arg upsertAgentForTeamParams) (Agent, error) {
	row := q.queryRow(ctx, q.upsertAgentForTeamStmt, upsertAgentForTeam,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Version,
		arg.Status,
		arg.ApiKey,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.HostID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
