// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_teams.sql

package db

import (
	"context"
)

const getTeamByAgentAPIKey = `-- name: GetTeamByAgentAPIKey :one
SELECT teams.id, teams.name, teams.created_at, teams.updated_at 
FROM teams
JOIN agents ON agents.team_id = teams.id
WHERE agents.api_key = ?1
`

func (q *Queries) GetTeamByAgentAPIKey(ctx context.Context, agentApiKey string) (Team, error) {
	row := q.queryRow(ctx, q.getTeamByAgentAPIKeyStmt, getTeamByAgentAPIKey, agentApiKey)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT teams.id, teams.name, teams.created_at, teams.updated_at  
FROM teams
WHERE id = ?1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.queryRow(ctx, q.getTeamByIDStmt, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: createTeam :one
INSERT INTO teams (name)
VALUES (?1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) createTeam(ctx context.Context, name string) (Team, error) {
	row := q.queryRow(ctx, q.createTeamStmt, createTeam, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
