// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_cpu_samples.sql

package db

import (
	"context"
)

const getLatestCPUSample = `-- name: GetLatestCPUSample :one
SELECT cpu_samples.id, cpu_samples.observed_at, cpu_samples.used_percent, cpu_samples.cores_logical, cpu_samples.cores_physical, cpu_samples.per_core_percent, cpu_samples.load_1m, cpu_samples.load_5m, cpu_samples.load_15m
FROM cpu_samples
ORDER BY observed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCPUSample(ctx context.Context) (CpuSample, error) {
	row := q.queryRow(ctx, q.getLatestCPUSampleStmt, getLatestCPUSample)
	var i CpuSample
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.UsedPercent,
		&i.CoresLogical,
		&i.CoresPhysical,
		&i.PerCorePercent,
		&i.Load1m,
		&i.Load5m,
		&i.Load15m,
	)
	return i, err
}

const listCPUSamplesSince = `-- name: ListCPUSamplesSince :many
SELECT cpu_samples.id, cpu_samples.observed_at, cpu_samples.used_percent, cpu_samples.cores_logical, cpu_samples.cores_physical, cpu_samples.per_core_percent, cpu_samples.load_1m, cpu_samples.load_5m, cpu_samples.load_15m
FROM cpu_samples
WHERE observed_at >= ?1
ORDER BY observed_at
`

func (q *Queries) ListCPUSamplesSince(ctx context.Context, since string) ([]CpuSample, error) {
	rows, err := q.query(ctx, q.listCPUSamplesSinceStmt, listCPUSamplesSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpuSample
	for rows.Next() {
		var i CpuSample
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.UsedPercent,
			&i.CoresLogical,
			&i.CoresPhysical,
			&i.PerCorePercent,
			&i.Load1m,
			&i.Load5m,
			&i.Load15m,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCPUSample = `-- name: createCPUSample :exec
INSERT INTO cpu_samples (
    observed_at,
    used_percent,
    cores_logical,
    cores_physical,
    per_core_percent,
    load_1m,
    load_5m,
    load_15m
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type createCPUSampleParams struct {
	ObservedAt     string  `db:"observed_at"`
	UsedPercent    float64 `db:"used_percent"`
	CoresLogical   int64   `db:"cores_logical"`
	CoresPhysical  int64   `db:"cores_physical"`
	PerCorePercent string  `db:"per_core_percent"`
	Load1m         float64 `db:"load_1m"`
	Load5m         float64 `db:"load_5m"`
	Load15m        float64 `db:"load_15m"`
}

func (q *Queries) createCPUSample(ctx context.Context, arg createCPUSampleParams) error {
	_, err := q.exec(ctx, q.createCPUSampleStmt, createCPUSample,
		arg.ObservedAt,
		arg.UsedPercent,
		arg.CoresLogical,
		arg.CoresPhysical,
		arg.PerCorePercent,
		arg.Load1m,
		arg.Load5m,
		arg.Load15m,
	)
	return err
}

const deleteOldCPUSamples = `-- name: deleteOldCPUSamples :exec
DELETE FROM cpu_samples
WHERE observed_at < ?1
`

func (q *Queries) deleteOldCPUSamples(ctx context.Context, cutoff string) error {
	_, err := q.exec(ctx, q.deleteOldCPUSamplesStmt, deleteOldCPUSamples, cutoff)
	return err
}
