// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const commitSessionQuery = `-- name: CommitSessionQuery :exec
INSERT INTO sessions (token, data, expiry)
VALUES (?1, ?2, ?3)
ON CONFLICT(token) DO UPDATE SET data = excluded.data, expiry = excluded.expiry
`

type CommitSessionQueryParams struct {
	Token  string    `db:"token"`
	Data   []byte    `db:"data"`
	Expiry time.Time `db:"expiry"`
}

func (q *Queries) CommitSessionQuery(ctx context.Context, arg CommitSessionQueryParams) error {
	_, err := q.db.ExecContext(ctx, commitSessionQuery, arg.Token, arg.Data, arg.Expiry)
	return err
}

const createCPUSampleQuery = `-- name: CreateCPUSampleQuery :exec
INSERT INTO cpu_samples (
    observed_at,
    used_percent,
    cores_logical,
    cores_physical,
    per_core_percent,
    load_1m,
    load_5m,
    load_15m
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type CreateCPUSampleQueryParams struct {
	ObservedAt     string  `db:"observed_at"`
	UsedPercent    float64 `db:"used_percent"`
	CoresLogical   int64   `db:"cores_logical"`
	CoresPhysical  int64   `db:"cores_physical"`
	PerCorePercent string  `db:"per_core_percent"`
	Load1m         float64 `db:"load_1m"`
	Load5m         float64 `db:"load_5m"`
	Load15m        float64 `db:"load_15m"`
}

func (q *Queries) CreateCPUSampleQuery(ctx context.Context, arg CreateCPUSampleQueryParams) error {
	_, err := q.db.ExecContext(ctx, createCPUSampleQuery,
		arg.ObservedAt,
		arg.UsedPercent,
		arg.CoresLogical,
		arg.CoresPhysical,
		arg.PerCorePercent,
		arg.Load1m,
		arg.Load5m,
		arg.Load15m,
	)
	return err
}

const createDiskSampleQuery = `-- name: CreateDiskSampleQuery :exec
INSERT INTO disk_samples (
    observed_at,
    is_total,
    device,
    mount,
    filesystem,
    used_percent,
    used_bytes,
    free_bytes,
    total_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type CreateDiskSampleQueryParams struct {
	ObservedAt  string  `db:"observed_at"`
	IsTotal     int64   `db:"is_total"`
	Device      string  `db:"device"`
	Mount       string  `db:"mount"`
	Filesystem  string  `db:"filesystem"`
	UsedPercent float64 `db:"used_percent"`
	UsedBytes   int64   `db:"used_bytes"`
	FreeBytes   int64   `db:"free_bytes"`
	TotalBytes  int64   `db:"total_bytes"`
}

func (q *Queries) CreateDiskSampleQuery(ctx context.Context, arg CreateDiskSampleQueryParams) error {
	_, err := q.db.ExecContext(ctx, createDiskSampleQuery,
		arg.ObservedAt,
		arg.IsTotal,
		arg.Device,
		arg.Mount,
		arg.Filesystem,
		arg.UsedPercent,
		arg.UsedBytes,
		arg.FreeBytes,
		arg.TotalBytes,
	)
	return err
}

const createMemorySampleQuery = `-- name: CreateMemorySampleQuery :exec
INSERT INTO memory_samples (
    observed_at,
    virtual_used_percent,
    virtual_used_bytes,
    virtual_available_bytes,
    virtual_total_bytes,
    swap_used_percent,
    swap_used_bytes,
    swap_available_bytes,
    swap_total_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type CreateMemorySampleQueryParams struct {
	ObservedAt            string  `db:"observed_at"`
	VirtualUsedPercent    float64 `db:"virtual_used_percent"`
	VirtualUsedBytes      int64   `db:"virtual_used_bytes"`
	VirtualAvailableBytes int64   `db:"virtual_available_bytes"`
	VirtualTotalBytes     int64   `db:"virtual_total_bytes"`
	SwapUsedPercent       float64 `db:"swap_used_percent"`
	SwapUsedBytes         int64   `db:"swap_used_bytes"`
	SwapAvailableBytes    int64   `db:"swap_available_bytes"`
	SwapTotalBytes        int64   `db:"swap_total_bytes"`
}

func (q *Queries) CreateMemorySampleQuery(ctx context.Context, arg CreateMemorySampleQueryParams) error {
	_, err := q.db.ExecContext(ctx, createMemorySampleQuery,
		arg.ObservedAt,
		arg.VirtualUsedPercent,
		arg.VirtualUsedBytes,
		arg.VirtualAvailableBytes,
		arg.VirtualTotalBytes,
		arg.SwapUsedPercent,
		arg.SwapUsedBytes,
		arg.SwapAvailableBytes,
		arg.SwapTotalBytes,
	)
	return err
}

const createTeamQuery = `-- name: CreateTeamQuery :one
INSERT INTO teams (name, agent_api_key)
VALUES (?1, ?2)
RETURNING id, name, agent_api_key, created_at, updated_at
`

type CreateTeamQueryParams struct {
	Name        string `db:"name"`
	AgentApiKey string `db:"agent_api_key"`
}

func (q *Queries) CreateTeamQuery(ctx context.Context, arg CreateTeamQueryParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeamQuery, arg.Name, arg.AgentApiKey)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AgentApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserQuery = `-- name: CreateUserQuery :one
INSERT INTO users (team_id, email, password_hash)
VALUES (?1, ?2, ?3)
RETURNING id, team_id, email, password_hash, created_at, updated_at
`

type CreateUserQueryParams struct {
	TeamID       int64          `db:"team_id"`
	Email        string         `db:"email"`
	PasswordHash sql.NullString `db:"password_hash"`
}

func (q *Queries) CreateUserQuery(ctx context.Context, arg CreateUserQueryParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserQuery, arg.TeamID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldCPUSamplesQuery = `-- name: DeleteOldCPUSamplesQuery :exec
DELETE FROM cpu_samples
WHERE observed_at < ?1
`

func (q *Queries) DeleteOldCPUSamplesQuery(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, deleteOldCPUSamplesQuery, cutoff)
	return err
}

const deleteOldDiskSamplesQuery = `-- name: DeleteOldDiskSamplesQuery :exec
DELETE FROM disk_samples
WHERE observed_at < ?1
`

func (q *Queries) DeleteOldDiskSamplesQuery(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, deleteOldDiskSamplesQuery, cutoff)
	return err
}

const deleteOldMemorySamplesQuery = `-- name: DeleteOldMemorySamplesQuery :exec
DELETE FROM memory_samples
WHERE observed_at < ?1
`

func (q *Queries) DeleteOldMemorySamplesQuery(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, deleteOldMemorySamplesQuery, cutoff)
	return err
}

const deleteSessionQuery = `-- name: DeleteSessionQuery :exec
DELETE FROM sessions
WHERE token = ?1
`

func (q *Queries) DeleteSessionQuery(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionQuery, token)
	return err
}

const findSessionQuery = `-- name: FindSessionQuery :one
SELECT data
FROM sessions
WHERE token = ?1
AND expiry > ?2
`

type FindSessionQueryParams struct {
	Token string    `db:"token"`
	Now   time.Time `db:"now"`
}

func (q *Queries) FindSessionQuery(ctx context.Context, arg FindSessionQueryParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, findSessionQuery, arg.Token, arg.Now)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getAgentForUserQuery = `-- name: GetAgentForUserQuery :one
SELECT agents.id, agents.user_id, agents.name, agents.version, agents.created_at, agents.updated_at
FROM agents
WHERE id = ?1
AND user_id = ?2
`

type GetAgentForUserQueryParams struct {
	ID     string `db:"id"`
	UserID int64  `db:"user_id"`
}

type GetAgentForUserQueryRow struct {
	Agent Agent `db:"agent"`
}

func (q *Queries) GetAgentForUserQuery(ctx context.Context, arg GetAgentForUserQueryParams) (GetAgentForUserQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentForUserQuery, arg.ID, arg.UserID)
	var i GetAgentForUserQueryRow
	err := row.Scan(
		&i.Agent.ID,
		&i.Agent.UserID,
		&i.Agent.Name,
		&i.Agent.Version,
		&i.Agent.CreatedAt,
		&i.Agent.UpdatedAt,
	)
	return i, err
}

const getFirstUserByTeamIDQuery = `-- name: GetFirstUserByTeamIDQuery :one
SELECT users.id, users.team_id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE team_id = ?1
ORDER BY id
LIMIT 1
`

type GetFirstUserByTeamIDQueryRow struct {
	User User `db:"user"`
}

func (q *Queries) GetFirstUserByTeamIDQuery(ctx context.Context, teamID int64) (GetFirstUserByTeamIDQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getFirstUserByTeamIDQuery, teamID)
	var i GetFirstUserByTeamIDQueryRow
	err := row.Scan(
		&i.User.ID,
		&i.User.TeamID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getLatestCPUSampleQuery = `-- name: GetLatestCPUSampleQuery :one
SELECT cpu_samples.id, cpu_samples.observed_at, cpu_samples.used_percent, cpu_samples.cores_logical, cpu_samples.cores_physical, cpu_samples.per_core_percent, cpu_samples.load_1m, cpu_samples.load_5m, cpu_samples.load_15m
FROM cpu_samples
ORDER BY observed_at DESC
LIMIT 1
`

type GetLatestCPUSampleQueryRow struct {
	CpuSample CpuSample `db:"cpu_sample"`
}

func (q *Queries) GetLatestCPUSampleQuery(ctx context.Context) (GetLatestCPUSampleQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestCPUSampleQuery)
	var i GetLatestCPUSampleQueryRow
	err := row.Scan(
		&i.CpuSample.ID,
		&i.CpuSample.ObservedAt,
		&i.CpuSample.UsedPercent,
		&i.CpuSample.CoresLogical,
		&i.CpuSample.CoresPhysical,
		&i.CpuSample.PerCorePercent,
		&i.CpuSample.Load1m,
		&i.CpuSample.Load5m,
		&i.CpuSample.Load15m,
	)
	return i, err
}

const getLatestMemorySampleQuery = `-- name: GetLatestMemorySampleQuery :one
SELECT memory_samples.id, memory_samples.observed_at, memory_samples.virtual_used_percent, memory_samples.virtual_used_bytes, memory_samples.virtual_available_bytes, memory_samples.virtual_total_bytes, memory_samples.swap_used_percent, memory_samples.swap_used_bytes, memory_samples.swap_available_bytes, memory_samples.swap_total_bytes
FROM memory_samples
ORDER BY observed_at DESC
LIMIT 1
`

type GetLatestMemorySampleQueryRow struct {
	MemorySample MemorySample `db:"memory_sample"`
}

func (q *Queries) GetLatestMemorySampleQuery(ctx context.Context) (GetLatestMemorySampleQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestMemorySampleQuery)
	var i GetLatestMemorySampleQueryRow
	err := row.Scan(
		&i.MemorySample.ID,
		&i.MemorySample.ObservedAt,
		&i.MemorySample.VirtualUsedPercent,
		&i.MemorySample.VirtualUsedBytes,
		&i.MemorySample.VirtualAvailableBytes,
		&i.MemorySample.VirtualTotalBytes,
		&i.MemorySample.SwapUsedPercent,
		&i.MemorySample.SwapUsedBytes,
		&i.MemorySample.SwapAvailableBytes,
		&i.MemorySample.SwapTotalBytes,
	)
	return i, err
}

const getTeamByAgentAPIKeyQuery = `-- name: GetTeamByAgentAPIKeyQuery :one
SELECT teams.id, teams.name, teams.agent_api_key, teams.created_at, teams.updated_at
FROM teams
WHERE agent_api_key = ?1
`

type GetTeamByAgentAPIKeyQueryRow struct {
	Team Team `db:"team"`
}

func (q *Queries) GetTeamByAgentAPIKeyQuery(ctx context.Context, agentApiKey string) (GetTeamByAgentAPIKeyQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getTeamByAgentAPIKeyQuery, agentApiKey)
	var i GetTeamByAgentAPIKeyQueryRow
	err := row.Scan(
		&i.Team.ID,
		&i.Team.Name,
		&i.Team.AgentApiKey,
		&i.Team.CreatedAt,
		&i.Team.UpdatedAt,
	)
	return i, err
}

const getTeamByIDQuery = `-- name: GetTeamByIDQuery :one
SELECT teams.id, teams.name, teams.agent_api_key, teams.created_at, teams.updated_at
FROM teams
WHERE id = ?1
`

type GetTeamByIDQueryRow struct {
	Team Team `db:"team"`
}

func (q *Queries) GetTeamByIDQuery(ctx context.Context, id int64) (GetTeamByIDQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getTeamByIDQuery, id)
	var i GetTeamByIDQueryRow
	err := row.Scan(
		&i.Team.ID,
		&i.Team.Name,
		&i.Team.AgentApiKey,
		&i.Team.CreatedAt,
		&i.Team.UpdatedAt,
	)
	return i, err
}

const getUserByEmailQuery = `-- name: GetUserByEmailQuery :one
SELECT users.id, users.team_id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE email = ?1
`

type GetUserByEmailQueryRow struct {
	User User `db:"user"`
}

func (q *Queries) GetUserByEmailQuery(ctx context.Context, email string) (GetUserByEmailQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailQuery, email)
	var i GetUserByEmailQueryRow
	err := row.Scan(
		&i.User.ID,
		&i.User.TeamID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getUserByIDQuery = `-- name: GetUserByIDQuery :one
SELECT users.id, users.team_id, users.email, users.password_hash, users.created_at, users.updated_at
FROM users
WHERE id = ?1
`

type GetUserByIDQueryRow struct {
	User User `db:"user"`
}

func (q *Queries) GetUserByIDQuery(ctx context.Context, id int64) (GetUserByIDQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDQuery, id)
	var i GetUserByIDQueryRow
	err := row.Scan(
		&i.User.ID,
		&i.User.TeamID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listAgentsForUserQuery = `-- name: ListAgentsForUserQuery :many
SELECT agents.id, agents.user_id, agents.name, agents.version, agents.created_at, agents.updated_at
FROM agents
WHERE user_id = ?1
ORDER BY updated_at DESC
`

type ListAgentsForUserQueryRow struct {
	Agent Agent `db:"agent"`
}

func (q *Queries) ListAgentsForUserQuery(ctx context.Context, userID int64) ([]ListAgentsForUserQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsForUserQuery, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsForUserQueryRow
	for rows.Next() {
		var i ListAgentsForUserQueryRow
		if err := rows.Scan(
			&i.Agent.ID,
			&i.Agent.UserID,
			&i.Agent.Name,
			&i.Agent.Version,
			&i.Agent.CreatedAt,
			&i.Agent.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCPUSamplesSinceQuery = `-- name: ListCPUSamplesSinceQuery :many
SELECT cpu_samples.id, cpu_samples.observed_at, cpu_samples.used_percent, cpu_samples.cores_logical, cpu_samples.cores_physical, cpu_samples.per_core_percent, cpu_samples.load_1m, cpu_samples.load_5m, cpu_samples.load_15m
FROM cpu_samples
WHERE observed_at >= ?1
ORDER BY observed_at
`

type ListCPUSamplesSinceQueryRow struct {
	CpuSample CpuSample `db:"cpu_sample"`
}

func (q *Queries) ListCPUSamplesSinceQuery(ctx context.Context, since string) ([]ListCPUSamplesSinceQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, listCPUSamplesSinceQuery, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCPUSamplesSinceQueryRow
	for rows.Next() {
		var i ListCPUSamplesSinceQueryRow
		if err := rows.Scan(
			&i.CpuSample.ID,
			&i.CpuSample.ObservedAt,
			&i.CpuSample.UsedPercent,
			&i.CpuSample.CoresLogical,
			&i.CpuSample.CoresPhysical,
			&i.CpuSample.PerCorePercent,
			&i.CpuSample.Load1m,
			&i.CpuSample.Load5m,
			&i.CpuSample.Load15m,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiskSamplesForMountSinceQuery = `-- name: ListDiskSamplesForMountSinceQuery :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE mount = ?1
  AND observed_at >= ?2
ORDER BY observed_at
`

type ListDiskSamplesForMountSinceQueryParams struct {
	Mount string `db:"mount"`
	Since string `db:"since"`
}

type ListDiskSamplesForMountSinceQueryRow struct {
	DiskSample DiskSample `db:"disk_sample"`
}

func (q *Queries) ListDiskSamplesForMountSinceQuery(ctx context.Context, arg ListDiskSamplesForMountSinceQueryParams) ([]ListDiskSamplesForMountSinceQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, listDiskSamplesForMountSinceQuery, arg.Mount, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiskSamplesForMountSinceQueryRow
	for rows.Next() {
		var i ListDiskSamplesForMountSinceQueryRow
		if err := rows.Scan(
			&i.DiskSample.ID,
			&i.DiskSample.ObservedAt,
			&i.DiskSample.IsTotal,
			&i.DiskSample.Device,
			&i.DiskSample.Mount,
			&i.DiskSample.Filesystem,
			&i.DiskSample.UsedPercent,
			&i.DiskSample.UsedBytes,
			&i.DiskSample.FreeBytes,
			&i.DiskSample.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiskSamplesSinceQuery = `-- name: ListDiskSamplesSinceQuery :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE observed_at >= ?1
ORDER BY observed_at, is_total DESC, mount
`

type ListDiskSamplesSinceQueryRow struct {
	DiskSample DiskSample `db:"disk_sample"`
}

func (q *Queries) ListDiskSamplesSinceQuery(ctx context.Context, since string) ([]ListDiskSamplesSinceQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, listDiskSamplesSinceQuery, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiskSamplesSinceQueryRow
	for rows.Next() {
		var i ListDiskSamplesSinceQueryRow
		if err := rows.Scan(
			&i.DiskSample.ID,
			&i.DiskSample.ObservedAt,
			&i.DiskSample.IsTotal,
			&i.DiskSample.Device,
			&i.DiskSample.Mount,
			&i.DiskSample.Filesystem,
			&i.DiskSample.UsedPercent,
			&i.DiskSample.UsedBytes,
			&i.DiskSample.FreeBytes,
			&i.DiskSample.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDiskSamplesQuery = `-- name: ListLatestDiskSamplesQuery :many
SELECT disk_samples.id, disk_samples.observed_at, disk_samples.is_total, disk_samples.device, disk_samples.mount, disk_samples.filesystem, disk_samples.used_percent, disk_samples.used_bytes, disk_samples.free_bytes, disk_samples.total_bytes
FROM disk_samples
WHERE observed_at = (
    SELECT MAX(observed_at)
    FROM disk_samples
)
ORDER BY is_total DESC, free_bytes, mount
`

type ListLatestDiskSamplesQueryRow struct {
	DiskSample DiskSample `db:"disk_sample"`
}

func (q *Queries) ListLatestDiskSamplesQuery(ctx context.Context) ([]ListLatestDiskSamplesQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestDiskSamplesQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestDiskSamplesQueryRow
	for rows.Next() {
		var i ListLatestDiskSamplesQueryRow
		if err := rows.Scan(
			&i.DiskSample.ID,
			&i.DiskSample.ObservedAt,
			&i.DiskSample.IsTotal,
			&i.DiskSample.Device,
			&i.DiskSample.Mount,
			&i.DiskSample.Filesystem,
			&i.DiskSample.UsedPercent,
			&i.DiskSample.UsedBytes,
			&i.DiskSample.FreeBytes,
			&i.DiskSample.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemorySamplesSinceQuery = `-- name: ListMemorySamplesSinceQuery :many
SELECT memory_samples.id, memory_samples.observed_at, memory_samples.virtual_used_percent, memory_samples.virtual_used_bytes, memory_samples.virtual_available_bytes, memory_samples.virtual_total_bytes, memory_samples.swap_used_percent, memory_samples.swap_used_bytes, memory_samples.swap_available_bytes, memory_samples.swap_total_bytes
FROM memory_samples
WHERE observed_at >= ?1
ORDER BY observed_at
`

type ListMemorySamplesSinceQueryRow struct {
	MemorySample MemorySample `db:"memory_sample"`
}

func (q *Queries) ListMemorySamplesSinceQuery(ctx context.Context, since string) ([]ListMemorySamplesSinceQueryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemorySamplesSinceQuery, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemorySamplesSinceQueryRow
	for rows.Next() {
		var i ListMemorySamplesSinceQueryRow
		if err := rows.Scan(
			&i.MemorySample.ID,
			&i.MemorySample.ObservedAt,
			&i.MemorySample.VirtualUsedPercent,
			&i.MemorySample.VirtualUsedBytes,
			&i.MemorySample.VirtualAvailableBytes,
			&i.MemorySample.VirtualTotalBytes,
			&i.MemorySample.SwapUsedPercent,
			&i.MemorySample.SwapUsedBytes,
			&i.MemorySample.SwapAvailableBytes,
			&i.MemorySample.SwapTotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAgentQuery = `-- name: TouchAgentQuery :exec
UPDATE agents
SET version = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type TouchAgentQueryParams struct {
	Version string `db:"version"`
	ID      string `db:"id"`
}

func (q *Queries) TouchAgentQuery(ctx context.Context, arg TouchAgentQueryParams) error {
	_, err := q.db.ExecContext(ctx, touchAgentQuery, arg.Version, arg.ID)
	return err
}

const upsertAgentForUserQuery = `-- name: UpsertAgentForUserQuery :one
INSERT INTO agents (id, user_id, name, version)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    version = excluded.version,
    updated_at = CURRENT_TIMESTAMP
WHERE agents.user_id = excluded.user_id
RETURNING id, user_id, name, version, created_at, updated_at
`

type UpsertAgentForUserQueryParams struct {
	ID      string `db:"id"`
	UserID  int64  `db:"user_id"`
	Name    string `db:"name"`
	Version string `db:"version"`
}

func (q *Queries) UpsertAgentForUserQuery(ctx context.Context, arg UpsertAgentForUserQueryParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentForUserQuery,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Version,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
